### ISSUE TITLE
Redirect to `http://keycloak:9009/realms/apisix/protocol/openid-connect/auth?state=...`

### ISSUE THREAD

**Issue by lrkwz** [ajavageek/authentication-keycloak-apisix#1]
Clone and `docker compose up`

Accessing to `http://localhost:9080/` I get redirected to KC and then back to `http://keycloak:9009` which won't work unless you change your `/etc/hosts` configuration

**Comment by nfrankel** [comment]
That's correct. It's mentioned in the [blog post](https://blog.frankel.ch/authentication-api-gateway/)
